### PR TITLE
Update ja locale.

### PR DESCRIPTION
**Pull request by tsuyoz**

### CODE REVIEW

**Comment by melloware** [comment]
Awesome!  By any chance would you volunteer to update the Japanese for PrimeFaces JSF as well?

JavaScript: https://github.com/primefaces/primefaces/tree/master/primefaces/src/main/resources/META-INF/resources/primefaces/locales

Messages: https://github.com/primefaces/primefaces/tree/master/primefaces/src/main/resources/org/primefaces

You can see we have no Japanese translations at all but it would be much appreciated!!!

**Review by melloware — APPROVED** [review]

**Comment by tsuyoz** [comment]
Hi,

Thank you for your suggestion!
I've just sent you a PR, please confirm.

Regards.

2023年2月19日(日) 21:47 Melloware ***@***.***>:

**Comment by melloware** [comment]
Thank you so much!

**Comment by melloware** [comment]
We just added new labels for Now and FileSizeTypes if you can update and send another PR?

**Pull request merged**
