### PR TITLE
French translation update

### PR DESCRIPTION
**Pull request by ShiftcodeDream**
Hi guys, I'm very happy to contribute again for a french PrimeLocale translation :-) Have a nice day, and an happy new year ! ;-)

For "am" and "pm" translation, it's ok for french people to use "am" and "pm". If you write "du matin" or "de l'apres midi" in your forms, french people will be very surprised because they don't use to see these "accademic" terms. Note that in France, hours are displayed from 00h00 to 23h59 included, so am / pm is not a casual usage.

For term "filter", there are two meanings : the common noun (example : please use this **filter**) and the verb (please **filter** all these stuff). French translation differs : common noun is "_filtre_" and verb "_filtrer_". I guess you need the verb, but in case I'm wrong, you are the 2 translations.

See you ;-)

### CODE REVIEW

**Comment by melloware** [comment]
I would use the Noun for "filter".  Thanks!!

**Comment by melloware** [comment]
Also remove "prevPageLabel" the correct one is "previousPageLabel"

**Review by melloware — CHANGES_REQUESTED** [review]
See comments

**Comment by ShiftcodeDream** [comment]
Asked adjustments done. Thanks for this great framework :-)

**Comment by melloware** [comment]
Thank you for contributing!!!

**Review by melloware — APPROVED** [review]

**Pull request merged**
