### PR TITLE
Add fa locale.

### PR DESCRIPTION
**Pull request by b4rdia**
Added Farsi locale for Persian language.

### CODE REVIEW

**Comment by melloware** [comment]
@b4rdia Is there any way I could get you to do a Farsi translation for PrimeFaces?  We have one but its old and basic.

In PrimeFaces we have two files to translate a client side and server side translation. Below are the two English full translations:

Client: [Client English JS File](https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-en.js)

Server: [Server English Properties File](https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/resources/org/primefaces/Messages_en.properties)

I know its asking a lot but the PF community would really appreciate it!

**Comment by b4rdia** [comment]
Yeah, I'd be happy to.

**Comment by melloware** [comment]
Thank you!  You can either paste me the files and I can submit the PR or however you want to do it.

**Comment by b4rdia** [comment]
@melloware Just submitted the [PR](https://github.com/primefaces/primefaces/pull/8220) for translations.

**Review by melloware — APPROVED** [review]

**Pull request merged**
