### PR TITLE
Update ja locale.

### PR DESCRIPTION
**Pull request by tsuyoz**

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
Thank you for the PR!

**Comment by melloware** [comment]
It looks like your True/False labels were not translated was that intentional?

```js
"trueLabel": "True",
"falseLabel": "False",
```

**Comment by tsuyoz** [comment]
Yes, a literal translation would sound strange, so I left it as is.

Regards.

2022年11月3日(木) 20:35 Melloware ***@***.***>:

**Comment by melloware** [comment]
Could I get you to submit another PR with new translations? See: https://github.com/primefaces/primelocale/blob/main/en.json

**Pull request merged**
