### PR TITLE
Add Croatian language support

### PR DESCRIPTION
**Pull request by davidmalis**
This PR adds a Croatian language support. 

Keep in mind that Croatian language does not have simple rules for singular/plural wording, so the following labels are translated in such a way that the number does not affect the phrasing:

 - hr.searchMessage 
 - hr.selectionMessage
 - hr.aria.stars
 
 __For example (with hr.searchMessage):__
 
Instead of:
 "1 dostupan rezultat", "2 dostupna rezultata"
  
 the label is passive:
 "Dostupno rezultata: 1", "Dostupno rezultata: 2" 
 
More flexible approach would be introducing ICU Message Format support into Prime libraries, so that we could do stuff like this:

```json
"aria": {
    "star": "{star, plural, one {1 zvijezda} few {{star} zvijezde} other {{star} zvijezdi}}"
 }
 ```
 
 but that is out of the scope of this work.

### CODE REVIEW

**Comment by melloware** [comment]
Awesome thank you for the PR!

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
I hope you don't mind I added your translation to PrimeFaces: https://github.com/primefaces/primefaces/pull/11118

PF has way more labels that do the 3 libs so a lot of it is still in English in the second part of the file.

**Comment by davidmalis** [comment]
@melloware, I translated the second part you've mentioned: [PR](https://github.com/melloware/primefaces/pull/368)

**Comment by melloware** [comment]
@davidmalis you totally rock!  The PF community thanks you.

**Pull request merged**
