### PR TITLE
Fixed #46 - Update 'en' locale for accessibility improvements

### LINKED ISSUE #46: Update 'en' locale for accessibility improvements
Please check [PrimeVue locale](https://github.com/primefaces/primevue/blob/master/components/config/PrimeVue.js#L7)

### PR DESCRIPTION
**Pull request by tugcekucukoglu**
Fix #46 - Update 'en' locale for accessibility improvements

### CODE REVIEW

**Comment by melloware** [comment]
It looks like you removed some options already in use in PrimeReact like "filter", "emptyMessage" etc.

**Review by melloware — CHANGES_REQUESTED** [review]
See comment

**Comment by melloware** [comment]
Sorry it looks like just `filter` was removed but is used in PrimeReact here: https://github.com/primefaces/primereact/blob/1ccd212569e8a6474d33371a253e67c7cc7f0759/components/lib/datatable/ColumnFilter.js#L391-L413

**Comment by tugcekucukoglu** [comment]
I guess I also miss `custom`.

**Comment by melloware** [comment]
I did a search I didn't find "custom" anywhere in PrimeREact so that one might be safe to remove?

**Comment by tugcekucukoglu** [comment]
It seems `custom` is an outdated locale. In any case, PrimeReact team will have decided its future. Personally, I prefer it to stay.

**Comment by melloware** [comment]
No problem thanks for the updates!

**Pull request merged**
