### PR TITLE
Create ms.json

### PR DESCRIPTION
**Pull request by aliuddinabdrauf**
for malay language

### CODE REVIEW

**Comment by aliuddinabdrauf** [comment]
please merge this for malay language

**Comment by melloware** [comment]
@aliuddinabdrauf  Is there any way I could get you to do a translation for PrimeFaces?  

In PrimeFaces we have two files to translate a client side and server side translation. Below are the two English full translations:

Client: [Client English JS File](https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-en.js)

Server: [Server English Properties File](https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/resources/org/primefaces/Messages_en.properties)

I know its asking a lot but the PF community would really appreciate it!

**Comment by aliuddinabdrauf** [comment]
np, i'll try my best

**Comment by melloware** [comment]
Thank you!

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
Wil merge this for now. Would be great if you could submit another PR with full translation.

**Pull request merged**
