### PR TITLE
Add ja locale.

### PR DESCRIPTION
**Pull request by tsuyoz**
Add Japanese locale.

### CODE REVIEW

**Comment by mertsincan** [comment]
Hi,

Thanks a lot for your contribution! 

Best Regards,

**Comment by melloware** [comment]
@tsuyoz Is there any way I could get you to do a Japanese translation for PrimeFaces?  

In PrimeFaces we have two files to translate a client side and server side translation. Below are the two English full translations:

Client: [Client English JS File](https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-en.js)

Server: [Server English Properties File](https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/resources/org/primefaces/Messages_en.properties)

I know its asking a lot but the PF community would really appreciate it!

**Comment by tsuyoz** [comment]
Hi there!
Thank you for contacting, about this work, I'll handle it!  

Happy holidays!

**Comment by melloware** [comment]
Thank you!  You can either paste me the files and I can submit the PR or however you want to do it.

**Pull request merged**
