### PR TITLE
corrected spanish translations

### PR DESCRIPTION
**Pull request by SoyDiego**
Corrected spanish translations

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
Added new label `"now": "Now",` to the English file if you don't mind adding it to yours?

**Comment by SoyDiego** [comment]
> Added new label `"now": "Now",` to the English file if you don't mind adding it to yours?

I can do it. I have create a new PR, right?

**Comment by SoyDiego** [comment]
> Yes please

No problem bro

**Comment by melloware** [comment]
Also Catalan if you happen to know that one? 😄

**Comment by SoyDiego** [comment]
> Also Catalan if you happen to know that one? 😄

Sure, I'm working with catalans here haha

**Pull request merged**
