### PR TITLE
refactor: ♻️ better arabic translation

### PR DESCRIPTION
**Pull request by mbadr2200**
add better and more generic translation for some arabic keys

### CODE REVIEW

**Comment by melloware** [comment]
Awesome!  Can you also add the missing "fileSizeTypes" key?

**Comment by melloware** [comment]
Actually two labels.

```js
"fileSizeTypes": ["B", "KB", "MB", "GB", "TB", "PB", "EB", "ZB", "YB"],
"now": "Now"
```

**Comment by melloware** [comment]
Great job!

**Comment by melloware** [comment]
Do you mind translating these for me for PrimeFaces?

```js
    "datatable.sort.ASC": "activate to sort column ascending",
    "datatable.sort.DESC": "activate to sort column descending",
    "datatable.sort.NONE": "activate to remove sorting on column",
    "spinner.INCREASE": "Increase Value",
    "spinner.DECREASE": "Decrease Value",
    "switch.ON": "On",
    "switch.OFF": "Off",
    "messages.ERROR": "Error",
    "messages.FATAL": "Fatal",
    "messages.INFO": "Information",
    "messages.WARN": "Warning",
```

**Comment by mbadr2200** [comment]
> Do you mind translating these for me for PrimeFaces JSF?
> 
> ```js
>     "datatable.sort.ASC": "activate to sort column ascending",
>     "datatable.sort.DESC": "activate to sort column descending",
>     "datatable.sort.NONE": "activate to remove sorting on column",
>     "spinner.INCREASE": "Increase Value",
>     "spinner.DECREASE": "Decrease Value",
>     "switch.ON": "On",
>     "switch.OFF": "Off",
>     "messages.ERROR": "Error",
>     "messages.FATAL": "Fatal",
>     "messages.INFO": "Information",
>     "messages.WARN": "Warning",
> ```

sure , at the same file right ?

**Comment by melloware** [comment]
no these are for PrimeFaces JSF specifically so you can just paste the translations here.

**Pull request merged**
